import { validateRegistry } from "../lib/schema";

export const offers = validateRegistry([
  {
    id: "zcode",
    name: "ZCode 限时免费",
    provider: "Z.ai",
    category: "limited-time",
    access: "application",
    evidence: "community",
    status: "provisional",
    description:
      "Community-tracked ZCode free campaign running 2026-09-03 to 2026-09-20. The official pricing page only lists GLM flash models as permanently free, so confirm the campaign inside the ZCode client before relying on it.",
    url: "https://z.ai",
    source: "https://docs.z.ai/guides/overview/pricing",
    actionUrl: "https://z.ai",
    limits: "Not published on the official pricing page; confirm in the ZCode client activity tab",
    expiry: "2026-09-20",
    caveat:
      "Campaign window comes from community tracking, not an official announcement. Requires explicit confirmation in the ZCode client.",
    lastVerified: "2026-09-17",
  },
  {
    id: "opencode-zen-union-alpha",
    name: "OpenCode Zen Union Alpha Free",
    provider: "OpenCode",
    category: "limited-time",
    access: "public",
    evidence: "official",
    status: "verified",
    description:
      "OpenCode Zen's zero-price Union Alpha lane: a stealth frontier multimodal model free for a limited time, with zero-retention privacy. Also free: MiMo-V2.5, Ling 3.0 Flash Fin, Nemotron 3 Ultra / 3.5 Lightning, Big Pickle, Muse Spark 1.3 Contributor.",
    url: "https://opencode.ai/docs/zen",
    source: "https://opencode.ai/docs/zen",
    actionUrl: "https://opencode.ai/auth",
    limits: "Free during the limited-time period; per-model caps not published",
    expiry: null,
    caveat:
      "Official page says limited time with no end date published. Some other free lanes (Big Pickle, MiMo, Ling, Nemotron) may use prompts for training; Union Alpha itself is zero-retention.",
    lastVerified: "2026-09-17",
  },
  {
    id: "aihubmix",
    name: "AIHubMix 免费模型",
    provider: "AIHubMix",
    category: "platform",
    access: "public",
    evidence: "official",
    status: "verified",
    description:
      "OpenAI-compatible and Anthropic-format gateway with dozens of free models, including gpt-5.5-free, gemini-3.8-flash-free, coding-glm-5.3-free, and coding-kimi-k3-free. No credit card, no trial expiry, quotas reset daily.",
    url: "https://aihubmix.com",
    source: "https://docs.aihubmix.com/en/blogs/free-ai-models",
    actionUrl: "https://aihubmix.com/token",
    limits:
      "Per free model, typically 5 requests/min, 100–500 requests/day, 1M tokens/day; some models publish no numbers",
    caveat: "GPT rows run on Azure with a content filter; Gemini rows are trial-grade and may 429.",
    lastVerified: "2026-09-17",
  },
  {
    id: "openrouter",
    name: "OpenRouter 免费层",
    provider: "OpenRouter",
    category: "platform",
    access: "public",
    evidence: "official",
    status: "verified",
    description:
      "Anonymous-access model gateway with a rotating set of :free models (about 20 today) plus zero-price non-free lanes such as stealth/union-alpha. One key, hundreds of models, works with any OpenAI-compatible tool.",
    url: "https://openrouter.ai",
    source: "https://openrouter.ai/docs/limits",
    actionUrl: "https://openrouter.ai",
    limits:
      ":free models: 20 requests/min; 50 requests/day without top-up, 1000/day after 10 lifetime credits (account-wide, shared across all free models)",
    caveat:
      "Daily cap is shared across every :free model on the account; stealth/union-alpha is priced 0 without the :free cap but its ceiling is unpublished.",
    lastVerified: "2026-09-17",
  },
  {
    id: "aweshare",
    name: "aweshare 社区 Hub",
    provider: "aweshare",
    category: "platform",
    access: "invite",
    evidence: "official",
    status: "verified",
    description:
      "Community model-sharing hub: producers expose their own backends (Ollama, vLLM, or API accounts) and consumers call them through standard OpenAI/Anthropic/Responses SDKs against one URL.",
    url: "https://aweshare.wehuman.top",
    source: "https://github.com/wehuman01/aweshare/blob/main/docs/community-hub/README_cn.md",
    actionUrl: "https://github.com/wehuman01/aweshare/blob/main/docs/community-hub/README_cn.md",
    limits: "Producer-defined concurrency and daily token budgets; hub admits a small number of consumers",
    caveat:
      "Invite-only, and all prompts transit the hub where the operator can see them. Sharing personal subscription keys may violate upstream terms; self-hosted open models are clean.",
    lastVerified: "2026-09-17",
  },
  {
    id: "openai-codex-oss",
    name: "Codex for Open Source",
    provider: "OpenAI",
    category: "application",
    access: "application",
    evidence: "official",
    status: "verified",
    description:
      "OpenAI program granting open-source maintainers free Codex access in recognition of public maintenance work.",
    source: "https://openai.com/form/codex-for-oss/",
    actionUrl: "https://openai.com/form/codex-for-oss/",
    limits: "Application-based; benefit size decided per applicant",
    caveat: "Requires an actively maintained open-source project.",
    lastVerified: "2026-09-17",
  },
  {
    id: "codex-students",
    name: "Codex for Students",
    provider: "OpenAI",
    category: "application",
    access: "student",
    evidence: "official",
    status: "verified",
    description:
      "Verified students get Codex access with API credits for 12 months, aimed at US and Canada schools at launch.",
    source: "https://developers.openai.com/community/students",
    actionUrl: "https://developers.openai.com/community/students",
    limits: "Reported as $100 in credits over 12 months for verified students",
    caveat: "Student verification required; availability has been US/Canada-first.",
    lastVerified: "2026-09-17",
  },
  {
    id: "stepfun-builder",
    name: "StepFun Builder Program",
    provider: "StepFun",
    category: "application",
    access: "application",
    evidence: "official",
    status: "verified",
    description:
      "Quarterly builder program: a two-minute form gets you model API access, Step Plan, AI Studio, and development quota, plus workshops and community. A separate education-verification channel accepts Xuexin materials.",
    url: "https://platform.stepfun.com",
    source: "https://platform.stepfun.com/builder-program",
    actionUrl: "https://platform.stepfun.com/builder-program",
    limits: "Application-based; quarterly cycles; projects can graduate to the Startup Program",
    caveat: "Individuals welcome; no business plan required.",
    lastVerified: "2026-09-17",
  },
  {
    id: "github-student",
    name: "GitHub Student Developer Pack",
    provider: "GitHub",
    category: "application",
    access: "student",
    evidence: "official",
    status: "verified",
    description:
      "The student pack bundles GitHub Pro, Copilot access, and a large catalog of partner tools for verified students.",
    url: "https://education.github.com",
    source: "https://education.github.com/pack",
    actionUrl: "https://education.github.com/pack",
    limits: "Renewed while student status stays verified",
    caveat: "Requires school-issued email or enrollment verification.",
    lastVerified: "2026-09-17",
  },
  {
    id: "zed",
    name: "Zed",
    provider: "Zed Industries",
    category: "application",
    access: "public",
    evidence: "official",
    status: "verified",
    description:
      "Free open-source (GPL) high-performance editor. Its built-in AI (Zeta) is subscription-based and grants no free inference credits; pair it with a free platform above via custom OpenAI-compatible providers instead.",
    url: "https://zed.dev",
    source: "https://github.com/zed-industries/zed",
    actionUrl: "https://zed.dev/download",
    limits: "Editor free forever; AI usage depends on the provider you connect",
    caveat: "Not a source of free model credits by itself.",
    lastVerified: "2026-09-17",
  },
]);
