import { validateRegistry } from "../lib/schema";

export const offers = validateRegistry([
  {
    id: "zcode",
    name: "ZCode",
    provider: "ZCode",
    category: "limited-time",
    access: "application",
    evidence: "community",
    status: "provisional",
    description:
      "Community-reported code-discount offer. Requires explicit client confirmation before relying on it.",
    caveat:
      "Requires explicit client confirmation; community-reported, not officially verified.",
  },
  {
    id: "opencode-zen-union-alpha",
    name: "OpenCode Zen Union Alpha",
    provider: "OpenCode",
    category: "limited-time",
    access: "invite",
    evidence: "official",
    status: "verified",
    description:
      "OpenCode Zen's zero-price Union Alpha lane, available for a limited time with no published end date.",
    source: "https://opencode.ai/docs/zen",
    actionUrl: "https://opencode.ai/auth",
    limits: "Limited time; end date not published",
    expiry: null,
  },
  {
    id: "aihubmix",
    name: "AIHubMix",
    provider: "AIHubMix",
    category: "platform",
    access: "public",
    evidence: "official",
    status: "verified",
    description:
      "Public AI platform aggregator offering access to multiple models through a unified interface.",
    url: "https://aihubmix.com",
    source: "AIHubMix official site",
    actionUrl: "https://aihubmix.com",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    provider: "OpenRouter",
    category: "platform",
    access: "public",
    evidence: "official",
    status: "verified",
    description:
      "Public platform providing unified API access to a wide range of LLMs from various providers.",
    url: "https://openrouter.ai",
    source: "OpenRouter official site",
    actionUrl: "https://openrouter.ai",
  },
  {
    id: "aweshare",
    name: "aweshare",
    provider: "aweshare",
    category: "platform",
    access: "invite",
    evidence: "official",
    status: "verified",
    description:
      "Invite-only model-sharing platform. Consider prompt transit and privacy implications before use.",
    caveat:
      "Invite-only; consider prompt transit and privacy implications before use.",
    source: "aweshare official documentation",
    actionUrl: "https://aweshare.dev",
  },
  {
    id: "openai-codex-oss",
    name: "OpenAI Codex OSS",
    provider: "OpenAI",
    category: "application",
    access: "public",
    evidence: "official",
    status: "verified",
    description:
      "Open-source codex application from OpenAI available for public use.",
    url: "https://github.com/openai/codex",
    source: "OpenAI GitHub",
    actionUrl: "https://github.com/openai/codex",
  },
  {
    id: "codex-students",
    name: "Codex Students",
    provider: "OpenAI",
    category: "application",
    access: "student",
    evidence: "official",
    status: "verified",
    description:
      "Student access tier for OpenAI Codex, available to verified students.",
    source: "OpenAI student program",
    actionUrl: "https://openai.com/student",
  },
  {
    id: "stepfun-builder",
    name: "StepFun Builder",
    provider: "StepFun",
    category: "application",
    access: "public",
    evidence: "official",
    status: "verified",
    description:
      "Public application builder platform provided by StepFun.",
    url: "https://stepfun.com",
    source: "StepFun official site",
    actionUrl: "https://stepfun.com",
  },
  {
    id: "github-student",
    name: "GitHub Student",
    provider: "GitHub",
    category: "application",
    access: "student",
    evidence: "official",
    status: "verified",
    description:
      "GitHub Student Developer Pack offering access to developer tools for verified students.",
    url: "https://education.github.com",
    source: "GitHub Education",
    actionUrl: "https://education.github.com",
  },
  {
    id: "zed",
    name: "Zed",
    provider: "Zed Industries",
    category: "application",
    access: "public",
    evidence: "official",
    status: "verified",
    description:
      "Public collaborative code editor available for general use.",
    url: "https://zed.dev",
    source: "Zed official site",
    actionUrl: "https://zed.dev",
  },
]);
